version: "3.6"

services:
  pocovidnet:
    container_name: ddev-${DDEV_SITENAME}-pocovidnet
    build: ../pocovidnet
    ports:
      - "8000:8000"
    volumes:
    - ".:/mnt/ddev_config"
    - "../data/tmp_images:/tmp_images"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
  web:
    depends_on:
      - pocovidnet
    links:
      - pocovidnet:pocovidnet