version: '3.6'

services:
  redis:
    container_name: ddev-${DDEV_SITENAME}-redis
    image: redis
    restart: "no"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=8983
    volumes:
      - type: bind
        source: ./redis
        target: /data
        consistency: cached
      - redisdata:/data
      - ".:/mnt/ddev_config"
  web:
    links:
    - redis:$DDEV_HOSTNAME
volumes:
  redisdata: