name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./pocovidscreen/resources/ui
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - working-directory: ${{env.working-directory}}
    - run: npm run prod
    - working-directory: ${{env.working-directory}}
      env:
        CI: true